server:
  port: 8888

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
       defaultZone: http://cloud7001.com:7001/eureka/
  instance:
    instance-id: Demo-Application
    prefer-ip-address: true     #访问路径可以显示IP地址


spring:
  mail:
    host: smtp.163.com
    username: killahadmin@163.com
    password: VWVBYZVTKZGIXXMZ
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#发送邮件使用
spark:
  system:
    work-id: 1
    data-center-id: 1
    host: smtp.163.com
    name: xxx
    #接收系统通知的邮箱，多个用,分割
    admins: 443890800@qq.com
    #通知短信接收手机
    admin-phones: 15907660001